### ISSUE TITLE
Vue Language Server Request textDocument/hover failed (v0.6.8)

### ISSUE THREAD

**Issue by cubodehelio** [octref/vetur#191]
I'm having this error repetitively. Seems like the last updates don't fix it.

```
[Error - 3:05:16 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/modes/embeddedSupport.js:9:35)
    at /home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/modes/languageModes.js:11:125
    at Object.get (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/languageModelCache.js:30:33)
    at /home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/modes/javascriptMode.js:16:43
    at Object.get (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/languageModelCache.js:30:33)
    at Object.getScriptKind (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/modes/javascriptMode.js:74:33)
    at Object.getScriptKind (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/node_modules/typescript/lib/typescript.js:71209:31)
    at HostCache.createEntry (/home/***/.vscode/extensions/octref.vetur-0.6.8/client/server/node_modules/typescript/lib/typescript.js:85685:36)
[Info  - 3:14:41 PM] Connection to server got closed. Server will restart.
vetur initialized
[Error - 3:24:31 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```

**Comment by octref** [comment]
Did you do this?

![image](https://cloud.githubusercontent.com/assets/4033249/25819332/9fdfca7a-33fb-11e7-86f8-652a35ed5768.png)

**Comment by cubodehelio** [comment]
ohh! my project is javascript only. Should I need to include `*.ts` anyway?

**Comment by octref** [comment]
The file you are opening is under `app/**/*.vue`, I suppose?

**Comment by octref** [comment]
The problem might be you do not have the correct typing dependency installed, and that's causing the signatureHelp failure.

`npm list` or `yarn list` output plz.

**Comment by rafaelpimpa** [comment]
Same here, vetur v0.6.8 and vscode v1.12.1, do not have ``tsconfig.json`` nor ``jsconfig.json``

``npm list``: https://pastebin.com/raw/8DGMYdPp

**Comment by cubodehelio** [comment]
This is the output for `npm list`.

```
testvue@1.0.0-alpha.2 /home/****/code/testvue
├── animate.css@3.5.2 extraneous
├─┬ autoprefixer@6.7.7
│ ├─┬ browserslist@1.7.7
│ │ └── electron-to-chromium@1.3.8
│ ├── caniuse-db@1.0.30000659
│ ├── normalize-range@0.1.2
│ ├── num2fraction@1.2.2
│ ├─┬ postcss@5.2.17
│ │ ├── js-base64@2.1.9
│ │ ├── source-map@0.5.6
│ │ └── supports-color@3.2.3
│ └── postcss-value-parser@3.3.0
├─┬ axios@0.16.1
│ └── follow-redirects@1.2.3
├─┬ babel-core@6.24.1
│ ├─┬ babel-code-frame@6.22.0
│ │ ├── esutils@2.0.2
│ │ └── js-tokens@3.0.1
│ ├─┬ babel-generator@6.24.1
│ │ ├─┬ detect-indent@4.0.0
│ │ │ └─┬ repeating@2.0.1
│ │ │   └── is-finite@1.0.2
│ │ ├── jsesc@1.3.0
│ │ ├── source-map@0.5.6
│ │ └── trim-right@1.0.1
│ ├── babel-helpers@6.24.1
│ ├── babel-messages@6.23.0
│ ├─┬ babel-runtime@6.23.0
│ │ └── regenerator-runtime@0.10.3
│ ├── babel-template@6.24.1
│ ├── babel-traverse@6.24.1
│ ├─┬ babel-types@6.24.1
│ │ ├── esutils@2.0.2
│ │ └── to-fast-properties@1.0.2
│ ├── babylon@6.17.0
│ ├── convert-source-map@1.5.0
│ ├─┬ debug@2.6.4
│ │ └── ms@0.7.3
│ ├── json5@0.5.1
│ ├── lodash@4.17.4
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.7
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ ├── path-is-absolute@1.0.1
│ ├── private@0.1.7
│ ├── slash@1.0.0
│ └── source-map@0.5.6
├─┬ babel-loader@6.4.1
│ ├─┬ find-cache-dir@0.1.1
│ │ ├── commondir@1.0.1
│ │ └── pkg-dir@1.0.0
│ ├─┬ loader-utils@0.2.17
│ │ ├── big.js@3.1.3
│ │ └── emojis-list@2.1.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── object-assign@4.1.1
├── babel-plugin-transform-runtime@6.23.0
├─┬ babel-preset-env@1.4.0
│ ├── babel-plugin-check-es2015-constants@6.22.0
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
│ ├─┬ babel-plugin-transform-async-to-generator@6.24.1
│ │ ├── babel-helper-remap-async-to-generator@6.24.1
│ │ └── babel-plugin-syntax-async-functions@6.13.0
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoping@6.24.1
│ ├─┬ babel-plugin-transform-es2015-classes@6.24.1
│ │ ├── babel-helper-define-map@6.24.1
│ │ ├── babel-helper-function-name@6.24.1
│ │ ├── babel-helper-optimise-call-expression@6.24.1
│ │ └── babel-helper-replace-supers@6.24.1
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1
│ ├── babel-plugin-transform-es2015-for-of@6.23.0
│ ├── babel-plugin-transform-es2015-function-name@6.24.1
│ ├── babel-plugin-transform-es2015-literals@6.22.0
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.1
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.24.1
│ │ └── babel-plugin-transform-strict-mode@6.24.1
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.24.1
│ │ └── babel-helper-hoist-variables@6.24.1
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.1
│ ├── babel-plugin-transform-es2015-object-super@6.24.1
│ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1
│ │ ├── babel-helper-call-delegate@6.24.1
│ │ └── babel-helper-get-function-arity@6.24.1
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1
│ ├── babel-plugin-transform-es2015-spread@6.22.0
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1
│ │ └── babel-helper-regex@6.24.1
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.24.1
│ │ └─┬ regexpu-core@2.0.0
│ │   ├── regenerate@1.3.2
│ │   ├── regjsgen@0.2.0
│ │   └─┬ regjsparser@0.1.5
│ │     └── jsesc@0.5.0
│ ├─┬ babel-plugin-transform-exponentiation-operator@6.24.1
│ │ ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
│ │ │ └── babel-helper-explode-assignable-expression@6.24.1
│ │ └── babel-plugin-syntax-exponentiation-operator@6.13.0
│ ├─┬ babel-plugin-transform-regenerator@6.24.1
│ │ └── regenerator-transform@0.9.11
│ └─┬ invariant@2.2.2
│   └── loose-envify@1.3.1
├─┬ babel-preset-stage-2@6.24.1
│ ├── babel-plugin-syntax-dynamic-import@6.18.0
│ ├─┬ babel-plugin-transform-class-properties@6.24.1
│ │ └── babel-plugin-syntax-class-properties@6.13.0
│ ├─┬ babel-plugin-transform-decorators@6.24.1
│ │ ├─┬ babel-helper-explode-class@6.24.1
│ │ │ └── babel-helper-bindify-decorators@6.24.1
│ │ └── babel-plugin-syntax-decorators@6.13.0
│ └─┬ babel-preset-stage-3@6.24.1
│   ├─┬ babel-plugin-transform-async-generator-functions@6.24.1
│   │ └── babel-plugin-syntax-async-generators@6.13.0
│   └─┬ babel-plugin-transform-object-rest-spread@6.23.0
│     └── babel-plugin-syntax-object-rest-spread@6.13.0
├─┬ babel-register@6.24.1
│ ├── core-js@2.4.1
│ ├─┬ home-or-tmp@2.0.0
│ │ ├── os-homedir@1.0.2
│ │ └── os-tmpdir@1.0.2
│ └─┬ source-map-support@0.4.14
│   └── source-map@0.5.6
├─┬ chalk@1.1.3
│ ├── ansi-styles@2.2.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ has-ansi@2.0.0
│ │ └── ansi-regex@2.1.1
│ ├── strip-ansi@3.0.1
│ └── supports-color@2.0.0
├── connect-history-api-fallback@1.3.0
├─┬ copy-webpack-plugin@4.0.1
│ ├── bluebird@2.11.0
│ ├─┬ fs-extra@0.26.7
│ │ ├── graceful-fs@4.1.11
│ │ ├── jsonfile@2.4.0
│ │ └── klaw@1.3.1
│ ├─┬ glob@6.0.4
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ └── once@1.4.0
│ ├─┬ is-glob@3.1.0
│ │ └── is-extglob@2.1.1
│ └── node-dir@0.1.16
├─┬ css-loader@0.28.0
│ ├─┬ css-selector-tokenizer@0.7.0
│ │ ├── cssesc@0.1.0
│ │ ├── fastparse@1.1.1
│ │ └── regexpu-core@1.0.0
│ ├─┬ cssnano@3.10.0
│ │ ├── decamelize@1.2.0
│ │ ├── defined@1.0.0
│ │ ├─┬ postcss-calc@5.3.1
│ │ │ ├── postcss-message-helpers@2.0.0
│ │ │ └─┬ reduce-css-calc@1.3.0
│ │ │   ├── math-expression-evaluator@1.2.16
│ │ │   └── reduce-function-call@1.0.2
│ │ ├─┬ postcss-colormin@2.2.2
│ │ │ └─┬ colormin@1.1.2
│ │ │   ├─┬ color@0.11.4
│ │ │   │ ├── clone@1.0.2
│ │ │   │ ├─┬ color-convert@1.9.0
│ │ │   │ │ └── color-name@1.1.2
│ │ │   │ └── color-string@0.3.0
│ │ │   └── css-color-names@0.0.4
│ │ ├── postcss-convert-values@2.6.1
│ │ ├── postcss-discard-comments@2.0.4
│ │ ├── postcss-discard-duplicates@2.1.0
│ │ ├── postcss-discard-empty@2.1.0
│ │ ├── postcss-discard-overridden@0.1.1
│ │ ├─┬ postcss-discard-unused@2.2.3
│ │ │ └── uniqs@2.0.0
│ │ ├─┬ postcss-filter-plugins@2.0.2
│ │ │ └─┬ uniqid@4.1.1
│ │ │   └── macaddress@0.2.8
│ │ ├── postcss-merge-idents@2.1.7
│ │ ├── postcss-merge-longhand@2.0.2
│ │ ├─┬ postcss-merge-rules@2.1.2
│ │ │ ├─┬ caniuse-api@1.6.1
│ │ │ │ ├── lodash.memoize@4.1.2
│ │ │ │ └── lodash.uniq@4.5.0
│ │ │ └── vendors@1.0.1
│ │ ├── postcss-minify-font-values@1.0.5
│ │ ├── postcss-minify-gradients@1.0.5
│ │ ├─┬ postcss-minify-params@1.2.2
│ │ │ └── alphanum-sort@1.0.2
│ │ ├── postcss-minify-selectors@2.1.1
│ │ ├── postcss-normalize-charset@1.1.1
│ │ ├─┬ postcss-normalize-url@3.0.8
│ │ │ ├── is-absolute-url@2.1.0
│ │ │ └─┬ normalize-url@1.9.1
│ │ │   ├── prepend-http@1.0.4
│ │ │   ├─┬ query-string@4.3.4
│ │ │   │ └── strict-uri-encode@1.1.0
│ │ │   └─┬ sort-keys@1.1.2
│ │ │     └── is-plain-obj@1.1.0
│ │ ├── postcss-ordered-values@2.2.3
│ │ ├── postcss-reduce-idents@2.4.0
│ │ ├── postcss-reduce-initial@1.0.1
│ │ ├── postcss-reduce-transforms@1.0.4
│ │ ├─┬ postcss-svgo@2.1.6
│ │ │ ├─┬ is-svg@2.1.0
│ │ │ │ └── html-comment-regex@1.1.1
│ │ │ └─┬ svgo@0.7.2
│ │ │   ├─┬ coa@1.0.1
│ │ │   │ └── q@1.5.0
│ │ │   ├── colors@1.1.2
│ │ │   ├─┬ csso@2.3.2
│ │ │   │ ├── clap@1.1.3
│ │ │   │ └── source-map@0.5.6
│ │ │   ├── sax@1.2.2
│ │ │   └── whet.extend@0.9.9
│ │ ├── postcss-unique-selectors@2.0.2
│ │ └── postcss-zindex@2.2.0
│ ├── loader-utils@1.1.0
│ ├── lodash.camelcase@4.3.0
│ ├── postcss-modules-extract-imports@1.0.1
│ ├─┬ postcss-modules-local-by-default@1.1.1
│ │ └─┬ css-selector-tokenizer@0.6.0
│ │   └── regexpu-core@1.0.0
│ ├─┬ postcss-modules-scope@1.0.2
│ │ └─┬ css-selector-tokenizer@0.6.0
│ │   └── regexpu-core@1.0.0
│ ├─┬ postcss-modules-values@1.2.2
│ │ └── icss-replace-symbols@1.0.2
│ └── source-list-map@0.1.8
├─┬ d3-geo-projection@2.1.0
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├── d3-array@1.2.0
│ └── d3-geo@1.6.3
├─┬ eslint@3.19.0
│ ├─┬ concat-stream@1.6.0
│ │ └── typedarray@0.0.6
│ ├─┬ doctrine@2.0.0
│ │ ├── esutils@2.0.2
│ │ └── isarray@1.0.0
│ ├─┬ escope@3.6.0
│ │ ├─┬ es6-map@0.1.5
│ │ │ ├── d@1.0.0
│ │ │ ├── es5-ext@0.10.15
│ │ │ ├── es6-iterator@2.0.1
│ │ │ ├── es6-set@0.1.5
│ │ │ ├── es6-symbol@3.1.1
│ │ │ └── event-emitter@0.3.5
│ │ ├── es6-weak-map@2.0.2
│ │ ├─┬ esrecurse@4.1.0
│ │ │ └── estraverse@4.1.1
│ │ └── estraverse@4.2.0
│ ├─┬ espree@3.4.2
│ │ ├── acorn@5.0.3
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├─┬ esquery@1.0.0
│ │ └── estraverse@4.2.0
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@2.0.0
│ │ └─┬ flat-cache@1.2.2
│ │   ├── circular-json@0.3.1
│ │   ├─┬ del@2.2.2
│ │   │ ├─┬ globby@5.0.0
│ │   │ │ ├─┬ array-union@1.0.2
│ │   │ │ │ └── array-uniq@1.0.3
│ │   │ │ └── glob@7.1.1
│ │   │ ├── is-path-cwd@1.0.0
│ │   │ └─┬ is-path-in-cwd@1.0.0
│ │   │   └── is-path-inside@1.0.0
│ │   └── write@0.2.1
│ ├─┬ glob@7.1.1
│ │ └── fs.realpath@1.0.0
│ ├── globals@9.17.0
│ ├── ignore@3.2.7
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@0.12.0
│ │ ├── ansi-escapes@1.4.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.1.0
│ │ ├── figures@1.7.0
│ │ ├─┬ readline2@1.0.1
│ │ │ ├── code-point-at@1.1.0
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ └── number-is-nan@1.0.1
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ ├── rx-lite@3.1.2
│ │ ├── string-width@1.0.2
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.16.0
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ └── jsonpointer@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.3
│ ├─┬ js-yaml@3.7.0
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.3
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├── natural-compare@1.4.0
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@2.0.6
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.2
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── strip-bom@3.0.0
│ ├── strip-json-comments@2.0.1
│ ├─┬ table@3.8.3
│ │ ├── slice-ansi@0.0.4
│ │ └─┬ string-width@2.0.0
│ │   └── is-fullwidth-code-point@2.0.0
│ ├── text-table@0.2.0
│ └── user-home@2.0.0
├── eslint-plugin-async-await@0.0.0
├─┬ eslint-plugin-html@2.0.1
│ └─┬ htmlparser2@3.9.2
│   ├── domelementtype@1.3.0
│   ├── domhandler@2.3.0
│   ├─┬ domutils@1.5.1
│   │ └─┬ dom-serializer@0.1.0
│   │   └── domelementtype@1.1.3
│   └── entities@1.1.1
├─┬ eslint-plugin-import@2.2.0
│ ├── builtin-modules@1.1.1
│ ├── contains-path@0.1.0
│ ├─┬ doctrine@1.5.0
│ │ └── esutils@2.0.2
│ ├─┬ eslint-import-resolver-node@0.2.3
│ │ └─┬ resolve@1.3.3
│ │   └── path-parse@1.0.5
│ ├─┬ eslint-module-utils@2.0.0
│ │ └─┬ debug@2.2.0
│ │   └── ms@0.7.1
│ ├─┬ has@1.0.1
│ │ └── function-bind@1.1.0
│ ├── lodash.cond@4.5.2
│ └─┬ pkg-up@1.0.0
│   └─┬ find-up@1.1.2
│     └── path-exists@2.1.0
├── eventsource-polyfill@0.9.6
├─┬ express@4.15.2
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.15
│ │ │ └── mime-db@1.27.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.6.1
│ │ └── ms@0.7.2
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.0
│ ├─┬ finalhandler@1.0.2
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.4
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.3.0
│ ├── qs@6.4.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.1
│ │ ├── debug@2.6.1
│ │ ├── destroy@1.0.4
│ │ ├── http-errors@1.6.1
│ │ └── ms@0.7.2
│ ├── serve-static@1.12.1
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.15
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.1
├─┬ extract-text-webpack-plugin@2.1.0
│ ├─┬ ajv@4.11.7
│ │ └── co@4.6.0
│ ├── async@2.3.0
│ ├── loader-utils@1.1.0
│ └─┬ webpack-sources@0.1.5
│   └── source-map@0.5.6
├─┬ file-loader@0.11.1
│ └── loader-utils@1.1.0
├─┬ foundation-sites@6.3.1
│ └── what-input@4.1.1
├─┬ friendly-errors-webpack-plugin@1.6.1
│ ├─┬ error-stack-parser@2.0.0
│ │ └── stackframe@1.0.2
│ └── string-length@1.0.1
├── fuse.js@3.0.0
├─┬ html-webpack-plugin@2.28.0
│ ├── bluebird@3.5.0
│ ├─┬ html-minifier@3.4.3
│ │ ├─┬ camel-case@3.0.0
│ │ │ ├─┬ no-case@2.3.1
│ │ │ │ └── lower-case@1.1.4
│ │ │ └── upper-case@1.1.3
│ │ ├─┬ clean-css@4.0.12
│ │ │ └── source-map@0.5.6
│ │ ├─┬ ncname@1.0.0
│ │ │ └── xml-char-classes@1.0.0
│ │ ├── param-case@2.1.1
│ │ └── relateurl@0.2.7
│ ├─┬ pretty-error@2.1.0
│ │ ├─┬ renderkid@2.0.1
│ │ │ ├─┬ css-select@1.2.0
│ │ │ │ ├── boolbase@1.0.0
│ │ │ │ ├── css-what@2.1.0
│ │ │ │ └── nth-check@1.0.1
│ │ │ ├─┬ dom-converter@0.1.4
│ │ │ │ └── utila@0.3.3
│ │ │ ├─┬ htmlparser2@3.3.0
│ │ │ │ ├── domhandler@2.1.0
│ │ │ │ ├── domutils@1.1.6
│ │ │ │ └─┬ readable-stream@1.0.34
│ │ │ │   ├── isarray@0.0.1
│ │ │ │   └── string_decoder@0.10.31
│ │ │ └── utila@0.3.3
│ │ └── utila@0.4.0
│ └── toposort@1.0.3
├─┬ http-proxy-middleware@0.17.4
│ ├─┬ http-proxy@1.16.2
│ │ ├── eventemitter3@1.2.0
│ │ └── requires-port@1.0.0
│ └─┬ micromatch@2.3.11
│   ├─┬ arr-diff@2.0.0
│   │ └── arr-flatten@1.0.3
│   ├── array-unique@0.2.1
│   ├─┬ braces@1.8.5
│   │ ├─┬ expand-range@1.8.2
│   │ │ └─┬ fill-range@2.2.3
│   │ │   ├── is-number@2.1.0
│   │ │   ├── isobject@2.1.0
│   │ │   ├── randomatic@1.1.6
│   │ │   └── repeat-string@1.6.1
│   │ ├── preserve@0.2.0
│   │ └── repeat-element@1.1.2
│   ├─┬ expand-brackets@0.1.5
│   │ └── is-posix-bracket@0.1.1
│   ├─┬ extglob@0.3.2
│   │ └── is-extglob@1.0.0
│   ├── filename-regex@2.0.0
│   ├── is-extglob@1.0.0
│   ├── is-glob@2.0.1
│   ├─┬ kind-of@3.1.0
│   │ └── is-buffer@1.1.5
│   ├─┬ normalize-path@2.1.1
│   │ └── remove-trailing-separator@1.0.1
│   ├─┬ object.omit@2.0.1
│   │ └── is-extendable@0.1.1
│   ├─┬ parse-glob@3.0.4
│   │ ├─┬ glob-base@0.3.0
│   │ │ └─┬ is-glob@2.0.1
│   │ │   └── is-extglob@1.0.0
│   │ ├── is-dotfile@1.0.2
│   │ ├── is-extglob@1.0.0
│   │ └── is-glob@2.0.1
│   └─┬ regex-cache@0.4.3
│     ├── is-equal-shallow@0.1.3
│     └── is-primitive@2.0.0
├── install@0.8.8 extraneous
├── jquery@3.2.1
├─┬ mapbox-gl@0.36.0
│ ├── @mapbox/gl-matrix@0.0.1
│ ├── @mapbox/shelf-pack@3.0.0
│ ├── @mapbox/unitbezier@0.0.0
│ ├── @mapbox/whoots-js@3.0.0
│ ├─┬ brfs@1.4.3
│ │ ├─┬ quote-stream@1.0.2
│ │ │ └── buffer-equal@0.0.1
│ │ └─┬ static-module@1.3.1
│ │   ├─┬ duplexer2@0.0.2
│ │   │ └─┬ readable-stream@1.1.14
│ │   │   ├── isarray@0.0.1
│ │   │   └── string_decoder@0.10.31
│ │   ├─┬ escodegen@1.3.3
│ │   │ ├── esprima@1.1.1
│ │   │ ├── estraverse@1.5.1
│ │   │ └── esutils@1.0.0
│ │   ├─┬ falafel@1.2.0
│ │   │ ├── acorn@1.2.2
│ │   │ ├── foreach@2.0.5
│ │   │ ├── isarray@0.0.1
│ │   │ └── object-keys@1.0.11
│ │   ├── object-inspect@0.4.0
│ │   ├─┬ quote-stream@0.0.0
│ │   │ └── minimist@0.0.8
│ │   ├─┬ readable-stream@1.0.34
│ │   │ ├── isarray@0.0.1
│ │   │ └── string_decoder@0.10.31
│ │   ├── shallow-copy@0.0.1
│ │   ├─┬ static-eval@0.2.4
│ │   │ └─┬ escodegen@0.0.28
│ │   │   ├── esprima@1.0.4
│ │   │   └── estraverse@1.3.2
│ │   └─┬ through2@0.4.2
│ │     └─┬ xtend@2.1.2
│ │       └── object-keys@0.4.0
│ ├─┬ bubleify@0.7.0
│ │ └─┬ buble@0.15.2
│ │   ├── acorn@3.3.0
│ │   ├─┬ acorn-object-spread@1.0.0
│ │   │ └── acorn@3.3.0
│ │   └── magic-string@0.14.0
│ ├── earcut@2.1.1
│ ├─┬ geojson-rewind@0.1.0
│ │ ├─┬ concat-stream@1.2.1
│ │ │ └─┬ bops@0.0.6
│ │ │   ├── base64-js@0.0.2
│ │ │   └── to-utf8@0.0.1
│ │ ├─┬ geojson-area@0.1.0
│ │ │ └── wgs84@0.0.0
│ │ └── minimist@0.0.5
│ ├── geojson-vt@2.4.0
│ ├── grid-index@1.0.0
│ ├── mapbox-gl-supported@1.2.0
│ ├─┬ package-json-versionify@1.0.4
│ │ └── browserify-package-json@1.0.1
│ ├─┬ pbf@1.3.7
│ │ ├── ieee754@1.1.8
│ │ └─┬ resolve-protobuf-schema@2.0.0
│ │   └── protocol-buffers-schema@2.2.0
│ ├── point-geometry@0.0.0
│ ├── quickselect@1.0.0
│ ├─┬ supercluster@2.3.0
│ │ └── kdbush@1.0.1
│ ├── tinyqueue@1.2.2
│ ├─┬ unassertify@2.0.4
│ │ ├── acorn@4.0.11
│ │ ├─┬ escodegen@1.8.1
│ │ │ ├── esprima@2.7.3
│ │ │ ├── estraverse@1.9.3
│ │ │ ├── esutils@2.0.2
│ │ │ └── source-map@0.2.0
│ │ ├─┬ multi-stage-sourcemap@0.2.1
│ │ │ └─┬ source-map@0.1.43
│ │ │   └── amdefine@1.0.1
│ │ └─┬ unassert@1.5.1
│ │   ├── acorn@4.0.11
│ │   ├─┬ call-matcher@1.0.1
│ │   │ └── estraverse@4.2.0
│ │   ├── deep-equal@1.0.1
│ │   ├── espurify@1.7.0
│ │   ├── estraverse@4.2.0
│ │   └── esutils@2.0.2
│ ├─┬ unflowify@1.0.1
│ │ └─┬ flow-remove-types@1.2.0
│ │   └── vlq@0.2.2
│ ├── vector-tile@1.3.0
│ ├── vt-pbf@2.1.2
│ └── webworkify@1.4.0
├── mezr@0.6.1
├─┬ node-sass@4.5.2
│ ├── async-foreach@0.1.3
│ ├─┬ cross-spawn@3.0.1
│ │ └─┬ which@1.2.14
│ │   └── isexe@2.0.0
│ ├── gaze@1.1.2
│ ├── get-stdin@4.0.1
│ ├── glob@7.1.1
│ ├── in-publish@2.0.0
│ ├── lodash.assign@4.2.0
│ ├── lodash.clonedeep@4.5.0
│ ├── lodash.mergewith@4.6.0
│ ├─┬ meow@3.7.0
│ │ ├─┬ camelcase-keys@2.1.0
│ │ │ └── camelcase@2.1.1
│ │ ├─┬ loud-rejection@1.6.0
│ │ │ ├─┬ currently-unhandled@0.4.1
│ │ │ │ └── array-find-index@1.0.2
│ │ │ └── signal-exit@3.0.2
│ │ ├── map-obj@1.0.1
│ │ ├── minimist@1.2.0
│ │ ├─┬ normalize-package-data@2.3.8
│ │ │ ├── hosted-git-info@2.4.2
│ │ │ ├── is-builtin-module@1.0.0
│ │ │ └─┬ validate-npm-package-license@3.0.1
│ │ │   ├─┬ spdx-correct@1.0.2
│ │ │   │ └── spdx-license-ids@1.2.2
│ │ │   └── spdx-expression-parse@1.0.4
│ │ ├─┬ read-pkg-up@1.0.1
│ │ │ └─┬ read-pkg@1.1.0
│ │ │   ├─┬ load-json-file@1.1.0
│ │ │   │ └─┬ strip-bom@2.0.0
│ │ │   │   └── is-utf8@0.2.1
│ │ │   └── path-type@1.1.0
│ │ ├─┬ redent@1.0.0
│ │ │ ├── indent-string@2.1.0
│ │ │ └── strip-indent@1.0.1
│ │ └── trim-newlines@1.0.0
│ ├── nan@2.6.2
│ ├─┬ node-gyp@3.6.1
│ │ ├── fstream@1.0.11
│ │ ├── glob@7.1.1
│ │ ├─┬ nopt@3.0.6
│ │ │ └── abbrev@1.1.0
│ │ ├── osenv@0.1.4
│ │ └─┬ tar@2.2.1
│ │   └── block-stream@0.0.9
│ ├─┬ npmlog@4.0.2
│ │ ├─┬ are-we-there-yet@1.1.4
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.7.4
│ │ │ ├── aproba@1.1.1
│ │ │ ├── has-unicode@2.0.1
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ ├─┬ request@2.81.0
│ │ ├── aws-sign2@0.6.0
│ │ ├── aws4@1.6.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.1.4
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@4.2.1
│ │ │ └── har-schema@1.0.5
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.4.0
│ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.13.0
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0
│ │ │   ├── bcrypt-pbkdf@1.0.1
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@0.2.0
│ │ ├── safe-buffer@5.0.1
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.3.2
│ │ ├── tunnel-agent@0.6.0
│ │ └── uuid@3.0.1
│ ├─┬ sass-graph@2.2.2
│ │ ├── glob@7.1.1
│ │ ├─┬ scss-tokenizer@0.2.1
│ │ │ └── source-map@0.4.4
│ │ └─┬ yargs@6.6.0
│ │   ├── camelcase@3.0.0
│ │   └── cliui@3.2.0
│ └── stdout-stream@1.4.0
├── npm@4.5.0 extraneous
├─┬ opn@4.0.2
│ └─┬ pinkie-promise@2.0.1
│   └── pinkie@2.0.4
├─┬ optimize-css-assets-webpack-plugin@1.3.1
│ └── underscore@1.8.3
├─┬ ora@1.2.0
│ ├─┬ cli-cursor@2.1.0
│ │ └─┬ restore-cursor@2.0.0
│ │   └─┬ onetime@2.0.1
│ │     └── mimic-fn@1.1.0
│ ├── cli-spinners@1.0.0
│ └── log-symbols@1.0.2
├── polylabel@1.0.2
├── pyrsmk-w@1.7.0
├─┬ rimraf@2.6.1
│ └── glob@7.1.1
├─┬ sass-lint@1.10.2
│ ├─┬ eslint@2.13.1
│ │ ├─┬ concat-stream@1.4.10
│ │ │ └─┬ readable-stream@1.1.14
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── doctrine@1.5.0
│ │ ├── estraverse@4.2.0
│ │ ├── esutils@2.0.2
│ │ ├── file-entry-cache@1.3.1
│ │ ├── shelljs@0.6.1
│ │ └── strip-json-comments@1.0.4
│ ├── front-matter@2.1.0
│ ├── fs-extra@1.0.0
│ ├── glob@7.1.1
│ ├─┬ globule@1.1.0
│ │ ├── glob@7.1.1
│ │ └── lodash@4.16.6
│ ├─┬ gonzales-pe@3.4.7
│ │ └── minimist@1.1.3
│ ├── lodash.capitalize@4.2.1
│ ├── lodash.kebabcase@4.1.1
│ ├── merge@1.2.0
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
├─┬ sass-loader@6.0.3
│ ├─┬ clone-deep@0.2.4
│ │ ├─┬ for-own@0.1.5
│ │ │ └── for-in@1.0.2
│ │ ├─┬ is-plain-object@2.0.1
│ │ │ └── isobject@1.0.2
│ │ ├── lazy-cache@1.0.4
│ │ └─┬ shallow-clone@0.1.2
│ │   ├── kind-of@2.0.1
│ │   ├── lazy-cache@0.2.7
│ │   └─┬ mixin-object@2.0.1
│ │     └── for-in@0.1.8
│ ├── loader-utils@1.1.0
│ ├── lodash.tail@4.1.1
│ └── pify@2.3.0
├── semver@5.3.0
├─┬ shapefile@0.6.2
│ ├── array-source@0.0.3
│ ├─┬ path-source@0.1.2
│ │ └── file-source@0.6.1
│ ├── slice-source@0.4.1
│ ├── stream-source@0.3.4
│ └── text-encoding@0.6.1
├─┬ shelljs@0.7.7
│ ├── glob@7.1.1
│ ├── interpret@1.0.3
│ └── rechoir@0.6.2
├─┬ through2@2.0.3
│ ├─┬ readable-stream@2.2.9
│ │ ├── buffer-shims@1.0.0
│ │ ├── core-util-is@1.0.2
│ │ ├── process-nextick-args@1.0.7
│ │ ├── string_decoder@1.0.0
│ │ └── util-deprecate@1.0.2
│ └── xtend@4.0.1
├── topojson-client@3.0.0
├── topojson-server@3.0.0
├── traverse@0.6.6
├── tween.js@16.6.0
├─┬ url-loader@0.5.8
│ ├── loader-utils@1.1.0
│ └── mime@1.3.4
├── vue@2.2.6
├─┬ vue-loader@11.3.4
│ ├─┬ consolidate@0.14.5
│ │ └── bluebird@3.5.0
│ ├── hash-sum@1.0.2
│ ├─┬ js-beautify@1.6.12
│ │ ├─┬ config-chain@1.1.11
│ │ │ ├── ini@1.3.4
│ │ │ └── proto-list@1.2.4
│ │ └─┬ editorconfig@0.13.2
│ │   ├── bluebird@3.5.0
│ │   ├── lru-cache@3.2.0
│ │   └── sigmund@1.0.1
│ ├── loader-utils@1.1.0
│ ├─┬ lru-cache@4.0.2
│ │ ├── pseudomap@1.0.2
│ │ └── yallist@2.1.2
│ ├─┬ postcss-load-config@1.2.0
│ │ ├─┬ cosmiconfig@2.1.1
│ │ │ ├─┬ parse-json@2.2.0
│ │ │ │ └─┬ error-ex@1.3.1
│ │ │ │   └── is-arrayish@0.2.1
│ │ │ └── require-from-string@1.2.1
│ │ ├── postcss-load-options@1.2.0
│ │ └── postcss-load-plugins@2.3.0
│ ├─┬ postcss-selector-parser@2.2.3
│ │ ├── flatten@1.0.2
│ │ ├── indexes-of@1.0.1
│ │ └── uniq@1.0.1
│ ├── source-map@0.5.6
│ ├── vue-hot-reload-api@2.1.0
│ └── vue-template-es2015-compiler@1.5.2
├── vue-material@0.7.1
├── vue-router@2.5.1
├─┬ vue-style-loader@2.0.5
│ └── loader-utils@1.1.0
├─┬ vue-template-compiler@2.2.6
│ ├── de-indent@1.0.2
│ └── he@1.1.1
├── vuex@2.3.1
├─┬ webpack@2.4.1
│ ├── acorn@5.0.3
│ ├─┬ acorn-dynamic-import@2.0.2
│ │ └── acorn@4.0.11
│ ├── ajv-keywords@1.5.1
│ ├── enhanced-resolve@3.1.0
│ ├── json-loader@0.5.4
│ ├── loader-runner@2.3.0
│ ├─┬ memory-fs@0.4.1
│ │ └─┬ errno@0.1.4
│ │   └── prr@0.0.0
│ ├─┬ node-libs-browser@2.0.0
│ │ ├── assert@1.4.1
│ │ ├─┬ browserify-zlib@0.1.4
│ │ │ └── pako@0.2.9
│ │ ├─┬ buffer@4.9.1
│ │ │ └── base64-js@1.2.0
│ │ ├─┬ console-browserify@1.1.0
│ │ │ └── date-now@0.1.4
│ │ ├── constants-browserify@1.0.0
│ │ ├─┬ crypto-browserify@3.11.0
│ │ │ ├─┬ browserify-cipher@1.0.0
│ │ │ │ ├─┬ browserify-aes@1.0.6
│ │ │ │ │ └── buffer-xor@1.0.3
│ │ │ │ ├─┬ browserify-des@1.0.0
│ │ │ │ │ └── des.js@1.0.0
│ │ │ │ └── evp_bytestokey@1.0.0
│ │ │ ├─┬ browserify-sign@4.0.4
│ │ │ │ ├── bn.js@4.11.6
│ │ │ │ ├── browserify-rsa@4.0.1
│ │ │ │ ├─┬ elliptic@6.4.0
│ │ │ │ │ ├── brorand@1.1.0
│ │ │ │ │ ├── hash.js@1.0.3
│ │ │ │ │ ├── hmac-drbg@1.0.1
│ │ │ │ │ ├── minimalistic-assert@1.0.0
│ │ │ │ │ └── minimalistic-crypto-utils@1.0.1
│ │ │ │ └─┬ parse-asn1@5.1.0
│ │ │ │   └── asn1.js@4.9.1
│ │ │ ├── create-ecdh@4.0.0
│ │ │ ├─┬ create-hash@1.1.2
│ │ │ │ ├── cipher-base@1.0.3
│ │ │ │ ├── ripemd160@1.0.1
│ │ │ │ └── sha.js@2.4.8
│ │ │ ├── create-hmac@1.1.4
│ │ │ ├─┬ diffie-hellman@5.0.2
│ │ │ │ └── miller-rabin@4.0.0
│ │ │ ├── pbkdf2@3.0.9
│ │ │ ├── public-encrypt@4.0.0
│ │ │ └── randombytes@2.0.3
│ │ ├── domain-browser@1.1.7
│ │ ├── events@1.1.1
│ │ ├── https-browserify@0.0.1
│ │ ├── os-browserify@0.2.1
│ │ ├── path-browserify@0.0.0
│ │ ├── process@0.11.9
│ │ ├── punycode@1.4.1
│ │ ├── querystring-es3@0.2.1
│ │ ├── stream-browserify@2.0.1
│ │ ├─┬ stream-http@2.7.0
│ │ │ ├── builtin-status-codes@3.0.0
│ │ │ └── to-arraybuffer@1.0.1
│ │ ├── string_decoder@0.10.31
│ │ ├─┬ timers-browserify@2.0.2
│ │ │ └── setimmediate@1.0.5
│ │ ├── tty-browserify@0.0.0
│ │ ├─┬ url@0.11.0
│ │ │ └── punycode@1.3.2
│ │ └─┬ vm-browserify@0.0.4
│ │   └── indexof@0.0.1
│ ├── source-map@0.5.6
│ ├─┬ supports-color@3.2.3
│ │ └── has-flag@1.0.0
│ ├── tapable@0.2.6
│ ├─┬ uglify-js@2.8.22
│ │ ├── source-map@0.5.6
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.10.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@2.1.0
│ │   │ ├─┬ center-align@0.1.3
│ │   │ │ └─┬ align-text@0.1.4
│ │   │ │   └── longest@1.0.1
│ │   │ ├── right-align@0.1.3
│ │   │ └── wordwrap@0.0.2
│ │   └── window-size@0.1.0
│ ├─┬ watchpack@1.3.1
│ │ └─┬ chokidar@1.6.1
│ │   ├─┬ anymatch@1.3.0
│ │   │ └── arrify@1.0.1
│ │   ├── async-each@1.0.1
│ │   ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
│ │   ├─┬ glob-parent@2.0.0
│ │   │ └─┬ is-glob@2.0.1
│ │   │   └── is-extglob@1.0.0
│ │   ├─┬ is-binary-path@1.0.1
│ │   │ └── binary-extensions@1.8.0
│ │   ├─┬ is-glob@2.0.1
│ │   │ └── is-extglob@1.0.0
│ │   └─┬ readdirp@2.1.0
│ │     └── set-immediate-shim@1.0.1
│ ├─┬ webpack-sources@0.2.3
│ │ └── source-list-map@1.1.1
│ └─┬ yargs@6.6.0
│   ├── camelcase@3.0.0
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.1.0
│   ├── get-caller-file@1.0.2
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── which-module@1.0.0
│   ├── y18n@3.2.1
│   └─┬ yargs-parser@4.2.1
│     └── camelcase@3.0.0
├─┬ webpack-bundle-analyzer@2.4.0
│ ├── acorn@5.0.3
│ ├── ejs@2.5.6
│ ├── filesize@3.5.6
│ ├─┬ gzip-size@3.0.0
│ │ └── duplexer@0.1.1
│ └── opener@1.4.3
├── webpack-dev-middleware@1.10.2
├─┬ webpack-hot-middleware@2.18.0
│ ├── ansi-html@0.0.7
│ ├── html-entities@1.2.1
│ └── querystring@0.2.0
└── webpack-merge@4.1.0
```

**Comment by octref** [comment]
OK, it's not dependency problem.

If you have opened this project previously with vetur, it has cache on language files. Can you try to rename the project (or move it to a different path), and see if it still crashes?

**Comment by rafaelpimpa** [comment]
Any way to remove the cache folder only?

**Comment by octref** [comment]
@rafaelpimpa Does that solve the crash?

There is no easy way to do that. You can rename -> reopen in VSCode -> name it back -> open again. I'll try to find a workaround...

**Comment by cubodehelio** [comment]
So far so good :D I'm still testing..

**Comment by cubodehelio** [comment]
mmm nope

```
vetur initialized
[Error - 5:20:13 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603
```

**Comment by rafaelpimpa** [comment]
``rename -> reopen in VSCode -> name it back -> open again``
Did this, but the error persists 😢 

```vetur initialized
[Error - 17:20:42] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 17:21:09] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 17:21:15] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 17:21:39] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603```

**Comment by octref** [comment]
@cubodehelio If this is just a toy project, do you mind sharing with me on GitHub? I can't repro it using vue's webpack template.

**Comment by rafaelpimpa** [comment]
Mine is [Buefy](https://github.com/rafaelpimpa/buefy)

**Comment by cubodehelio** [comment]
Sorry it's not a toy project, but I will try to start a new one tomorrow just as I did this one to see if I can reproduce it and in that case a will share it with you. Thank you!

May be @rafaelpimpa can help on this. @rafaelpimpa does your project includes the `jsconfig.json` or the `tsconfig.json`? as far as a understand this is necessary

**Comment by jing2si** [comment]
@octref 
### Reproducible Steps
Use cursor hover 'data2' in 'this.data2 = 1'
```
<template>
</template>
<script>
export default {
  watch: {
    data1 (val) {
      this.data2 = 1
    },
    data2 (val) {}
  }
}
</script>
```

![1](https://cloud.githubusercontent.com/assets/2288824/25888688/ae78fdaa-3599-11e7-8555-66e17e675f72.gif)

**Comment by octref** [comment]
@jing2si Thanks, that would be super helpful for debugging.

**Comment by seancheung** [comment]
Always got these when command/control + hovering. Especially when the file is being edited but not saved and not ready for compiling.
I think this extension is compiling the edited files while they have errors(like incomplete expressions).

**Comment by octref** [comment]
Does 0.6.11 still have the problem?

**Comment by rafaelpimpa** [comment]
It does.

**Comment by octref** [comment]
This is fixed by swallowing the error when no definition is found for the file. Will be published soon.
Also, when Vue 2.4 releases with new type definitions, `this.data2` will actually become typed.
Stay tuned 😉

**Comment by rafaelpimpa** [comment]
Kinda offtopic but where do you see next vue features? :D

**Comment by octref** [comment]
@rafaelpimpa I know a TS folk is working on this feature for 2.4 :-)

**Comment by nextgensparx** [comment]
@octref Any update on this? I still experience the issue described by @jing2si except Vetur now swallows the error. If just one imported component modifies a watched variable, the extension crashes making it unusable.

Vue 2.4 has been released so can this be fixed now?

**Comment by octref** [comment]
@nextgensparx I cannot repro the problem any more. Please open a new issue with repro steps.

**Comment by nextgensparx** [comment]
@octref I created a new issue #751
